### ISSUE TITLE
Not really an issue, more of a comment

### ISSUE THREAD

**Issue by StevenACoffman** [sgerrand/docker-smbpasswd#2]
I just wanted to say thank you! I modified your code to technically comply with periodic mandatory password change policies and then reset the password back to the original. You can check it out here: [subvert-periodic-password-change](https://github.com/StevenACoffman/subvert-periodic-password-change)

I didn't fork your repo, because the purpose of yours is different, and I didn't want to to confuse people, but I did give you credit in the readme.

**Comment by sgerrand** [comment]
I'm glad you found it useful.
